### ISSUE TITLE
npm install安装不上

### ISSUE THREAD

**Issue by samyhd** [ncform/ncform#67]
使用 npm i @ncform/ncform @ncform/ncform-common --save
安装不上，提示什么 

npm ERR! path D:\Web\node_modules\chalk\node_modules\has-ansi
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\Web\node_modules\chalk\node_modules\has-ansi'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

用阿里的 cnpm 提示找不到

能否提供不带@的或CNPM的安装途径，谢谢？

**Comment by samyhd** [comment]
$ cnpm install @ncform/ncform 
提示

× Install fail! Error: [@ncform/ncform@1.2.0 › @ncform/ncform-common@^1.2.0] Can't find package @ncform/ncform-common@^1.2.0
Error: [@ncform/ncform@1.2.0 › @ncform/ncform-common@^1.2.0] Can't find package @ncform/ncform-common@^1.2.0
    at resolve (C:\Users\SAM\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:78:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\SAM\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.20.2

**Comment by samyhd** [comment]
我的npm问题，删除package-lock.json再安装就可以了。
